### PR TITLE
allow an alternate form of key

### PR DESCRIPTION
**Pull request by diclophis**
This is the header the iOS client uses

### CODE REVIEW

**Comment by emersion** [comment]
For now, there are two keys: `javascriptKey` and `restKey`. Could you instead add a new separate key `clientKey`? That would make more sense.

**Comment by diclophis** [comment]
It should also be noted that you have to add a objective-c category and re-map (`api/1` to `/1`) for this to work with `Parse.framework`

    @implementation PFInternalUtils(UnParse)
    + (NSString *)parseServerURLString {
        return @"http://your-app-dot.net/1";
    }
    @end

I was able to get this running in https://flynn.io/ without a problem! Thanks for your work!

**Comment by emersion** [comment]
Thanks, good to hear that! :-)

Could you open a new pull request to explain how to make Unparse work with the Objective-C `Parse.framework` in `README.md`?

**Comment by diclophis** [comment]
Ok, will do

**Pull request merged**
